import json

# JSONL data as a string
jsonl_data = """{"id":67,"text":"Sarita Lama\\n\\nContact Information:\\n\\nPhone: +977-9812345678\\nEmail: sarita.lama@gmail.com\\nAddress: Kathmandu, Nepal\\nCareer Objective:\\nDedicated Quality Assurance Engineer with 3 years of experience in ensuring the quality of software applications. Looking to leverage expertise in QA methodologies in a challenging role.\\n\\nEducation:\\n\\nTribhuvan University\\nBachelor of Computer Science and Information Technology\\nPassed Year: 2018\\nProfessional Experience:\\n\\nNcell Pvt. Ltd.\\nQA Engineer\\nMarch 2021 – Present\\n\\nConducted manual and automated testing of web applications.\\nDeveloped test cases and test plans for new features.\\nCollaborated with developers to resolve defects and ensure software quality.\\nSkills:\\n\\nManual Testing, Automated Testing, Selenium, JIRA, Agile\\/Scrum\\nTest Case Development, Git, Jenkins\\nProjects:\\n\\nE-commerce Platform Testing\\n\\nConducted end-to-end testing of an e-commerce platform.\\nDeveloped and executed test cases for various features.\\nHealthcare Portal Testing\\n\\nPerformed manual and automated testing of a healthcare portal.\\nIdentified and reported defects, ensuring timely resolution.\\nRaju Shrestha\\n\\nContact Information:\\n\\nPhone: +977-9845678901\\nEmail: raju.shrestha@gmail.com\\nAddress: Bhaktapur, Nepal\\nCareer Objective:\\nExperienced Quality Assurance Engineer with 4 years of expertise in testing software applications. Seeking to apply skills in a dynamic and innovative environment.\\n\\nEducation:\\n\\nKathmandu University\\nBachelor of Engineering in Computer Engineering\\nPassed Year: 2017\\nProfessional Experience:\\n\\nF1Soft International\\nSenior QA Engineer\\nJune 2020 – Present\\n\\nDeveloped and executed test plans and test cases for web applications.\\nConducted automated testing using Selenium and JUnit.\\nCollaborated with development teams to ensure software quality.\\nSkills:\\n\\nManual Testing, Automated Testing, Selenium, JUnit, JIRA\\nTest Plan Development, Git, Jenkins, Agile\\/Scrum\\nProjects:\\n\\nProject Management Tool Testing\\n\\nDeveloped and executed test plans for a project management tool.\\nConducted automated testing using Selenium.\\nOnline Learning Platform Testing\\n\\nPerformed end-to-end testing of an online learning platform.\\nIdentified and reported defects, ensuring timely resolution.","label":[[0,11,"Name"],[13,33,"skills"],[42,57,"Name"]],"Comments":[]}
{"id":68,"text":"Anil Gurung\\n\\nContact Information:\\n\\nPhone: +977-9865432109\\nEmail: anil.gurung@gmail.com\\nAddress: Lalitpur, Nepal\\nCareer Objective:\\nSkilled AI Engineer with 5 years of experience in developing AI models. Looking to contribute to a forward-thinking team.\\n\\nEducation:\\n\\nNepal Engineering College\\nBachelor of Computer Engineering\\nPassed Year: 2016\\nProfessional Experience:\\n\\nLogPoint\\nLead AI Engineer\\nFebruary 2019 – Present\\n\\nLed the development of AI models using Python and TensorFlow.\\nImplemented NLP algorithms for text analysis and processing.\\nCollaborated with data scientists to build and deploy AI solutions.\\nSkills:\\n\\nPython, TensorFlow, Keras, Natural Language Processing, Machine Learning\\nGit, Docker, Jenkins, Agile\\/Scrum\\nProjects:\\n\\nChatbot Development\\n\\nBuilt a chatbot for customer support using NLP and machine learning.\\nIntegrated the chatbot with popular messaging platforms.\\nImage Classification\\n\\nDeveloped an image classification model using convolutional neural networks.\\nDeployed the model for real-time image analysis and prediction.\\n","label":[[0,11,"Name"],[42,57,"skills"],[95,111,"Name"]],"Comments":[]}
{"id":69,"text":"Anita Maharjan\\n\\nContact Information:\\n\\nPhone: +977-9846789012\\nEmail: anita.maharjan@gmail.com\\nAddress: Lalitpur, Nepal\\nCareer Objective:\\nExperienced Quality Assurance Engineer with 4 years of experience in ensuring software quality through meticulous testing. Aiming to contribute to a dynamic and innovative team.\\n\\nEducation:\\n\\nPurbanchal University\\nBachelor of Information Technology\\nPassed Year: 2017\\nProfessional Experience:\\n\\nMercantile Communications\\nSenior QA Engineer\\nMay 2020 – Present\\n\\nDeveloped and executed comprehensive test plans and test cases.\\nPerformed manual and automated testing of web and mobile applications.\\nIdentified, documented, and tracked software defects.\\nSkills:\\n\\nManual Testing, Automated Testing, Selenium, Appium, JIRA\\nTest Plan Development, Git, Jenkins, Agile\\/Scrum\\nProjects:\\n\\nSocial Media Application Testing\\n\\nConducted end-to-end testing for a social media application.\\nAutomated test scripts to enhance testing efficiency.\\nTravel Booking Platform Testing\\n\\nPerformed functional and performance testing of a travel booking platform.\\nEnsured the application met all user requirements and performance standards.","label":[],"Comments":[]}
{"id":70,"text":"Anjali Shrestha\\n\\nContact Information:\\n\\nPhone: +977-9812345678\\nEmail: anjali.shrestha@gmail.com\\nAddress: Chitwan, Nepal\\nCareer Objective:\\nExperienced Data Engineer with 5 years of expertise in building and maintaining data pipelines. Looking to contribute to a forward-thinking company.\\n\\nEducation:\\n\\nNepal Engineering College\\nBachelor of Computer Engineering\\nPassed Year: 2015\\nProfessional Experience:\\n\\nDeerwalk Inc.\\nData Engineer\\nJune 2017 – Present\\n\\nDeveloped and maintained data pipelines for ETL processes.\\nImplemented data warehousing solutions using SQL and NoSQL databases.\\nCollaborated with data scientists to ensure data quality and consistency.\\nSkills:\\n\\nPython, SQL, Apache Spark, Hadoop, ETL\\nData Warehousing, Data Modeling, Git, Docker\\nProjects:\\n\\nData Warehouse Development\\n\\nDeveloped a data warehouse for a healthcare application.\\nImplemented ETL processes to ensure data consistency.\\nMachine Learning Data Pipeline\\n\\nBuilt a data pipeline for machine learning applications.\\nIntegrated the pipeline with data visualization tools.\\n","label":[[137,399,"Name"]],"Comments":[]}"""

# Split the JSONL string into individual lines
lines = jsonl_data.strip().split('\n')

# Parse each line as JSON and add to a list
json_data = [json.loads(line) for line in lines]

# Convert the list to a JSON formatted string
json_output = json.dumps(json_data, indent=4)

# Print the JSON output
print(json_output)
